### PR TITLE
Delete ic_insert_photo_white_48dp.xml

### PR DESCRIPTION
**Pull request by Jawnnypoo**
I don't think this asset should ship with the library

### CODE REVIEW

**Comment by jkwiecien** [comment]
Why should it?

**Comment by Jawnnypoo** [comment]
Is it being used in the library anywhere? Otherwise it is just bloat within the library

**Comment by jkwiecien** [comment]
Oh it shouldn't...misunderstood you

**Comment by Jawnnypoo** [comment]
No worries 👍

**Pull request merged**
