### PR TITLE
Bug fix where canceled images would not be deleted and some additions

### PR DESCRIPTION
**Pull request by MarcRubio**
I believe commits provide enough of a description to what was done. Read me page would have to be changed if you agree with changes.

I updated the sample app too.

### CODE REVIEW

**Comment by jkwiecien** [comment]
Hey, thanks for your contribution. I started reviewing that, some really cool stuff there, but could you please go through all the changes and restore my original code style everywhere? That's a lot of changes of just code style. Just use default Android Studio formatter for that.

**Comment by MarcRubio** [comment]
Hi, thanks for reviewing.
1. Notation change: no problem
2. Permissions: Depending on where the user decides to save the file, either in root or in the app directory, the user should use one of those permissions.
Permission to write in the sdcard in the app directory is not required after sdk version 18 hence the maxSdkVersion.
Permission to write to root of sdcard on the other hand is required.
3. Code formatting: Sorry about that. Could you let me know your Code style right margin (columns) number found in Android Studio settings? Some sort of limit should be imposed, if not we could end up we very long lines.

I will make the changes by the end of the day. I was also thinking of changing a couple of minor things to my changes which I believe make even more sense.

**Comment by jkwiecien** [comment]
I use default Android Studio formatter, haven't done any changes. It doesn't wrap lines for me, no matter how long are them. I do it manually if the line is really long.

**Comment by MarcRubio** [comment]
Ok, so in the line where we have many "OR's" this is quite long. Do you want to keep this as a single line?

**Comment by jkwiecien** [comment]
Just restore all the codestyle changes you've made so I could review the important stuff. We might think about shortening those lines but in the separate commit.

**Comment by MarcRubio** [comment]
Ok, no problem!

**Comment by MarcRubio** [comment]
Hi, I am aware this latest commit isn't what you were asking for hence I am closing this request and creating a new one with a new new branch which should do exactly what you asked!

**Pull request closed without merging**
