### PR TITLE
This one should keep things clear with code style maintained.

### PR DESCRIPTION
**Pull request by MarcRubio**
Code style should be mostly maintained apart from a couple of odd lines. 

I added an extra method to clear configuration. 
If there is anything else, let me know!

### CODE REVIEW

**Comment by jkwiecien** [comment]
Pick from gallery doesn't really work on my Nexus5X, neither on genymotion. Gallery gets open, but after picking an image it doesn't show up in the sample area

**Comment by MarcRubio** [comment]
You are right, things were not working like they were supposed to!

After some testing, debugging and comparing with another project were it used to work fine, I narrowed it down to, for some reason, being related to the build tools. Everything worked fine with build tools 1.2.0 but it seems the updated versions changed things. 

Also as you said, it seems like permissions were involved with the problem but I can guarantee you this same code was being used and was working on this other project I have without any declared permission.

The joy of Android inconsistencies!

Regardless of all this, I have simply deleted the method which was the culprit and make use the one you provided which creates the temp image and makes everything work perfectly now. Doing it with your method also has the advantage of being able to load an image from the cloud from google photos which the deleted method failed to do.

I have tested on a jellybean device, rooted kitkat, lollipop 5.1 and nexus 9 marshmallow!

**Comment by jkwiecien** [comment]
I don't see any commits pushed to your repo, have you forgot to do that? :)

**Comment by MarcRubio** [comment]
The commits were pushed and appear fine on this convo screen above my long comment. They also appear fine on the commits tab. The repo is the keepstyle branch.

**Comment by jkwiecien** [comment]
Right... the branch! :)

**Comment by jkwiecien** [comment]
You haven't tested on most troublesome set of the devices which are ... samsungs ;)

Adding this real pick from gallery feature is a rocky path. My company collegues did similar library and said they had to do several hacks so it works with some of the manufacturers galleries. 

Wasn't surprise but it doesn't work with the samsung stock gallery app. See the stacktrace:
It is 5.0.1 Galaxy S5 - permissions :)

```java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media/102 from pid=18439, uid=10281 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
11-25 11:28:11.659 18439-18439/pl.aprilapps.easyphotopicker.sample W/System.err:     at android.os.Parcel.readException(Parcel.java:1540)
11-25 11:28:11.659 18439-18439/pl.aprilapps.easyphotopicker.sample W/System.err:     at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:185)
11-25 11:28:11.659 18439-18439/pl.aprilapps.easyphotopicker.sample W/System.err:     at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:148)
11-25 11:28:11.659 18439-18439/pl.aprilapps.easyphotopicker.sample W/System.err:     at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:689)
11-25 11:28:11.659 18439-18439/pl.aprilapps.easyphotopicker.sample W/System.err:     at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1088)
11-25 11:28:11.659 18439-18439/pl.aprilapps.easyphotopicker.sample W/System.err:     at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:927)
11-25 11:28:11.659 18439-18439/pl.aprilapps.easyphotopicker.sample W/System.err:     at android.content.ContentResolver.openInputStream(ContentResolver.java:652)
11-25 11:28:11.659 18439-18439/pl.aprilapps.easyphotopicker.sample W/System.err:     at pl.aprilapps.easyphotopicker.EasyImage.pickedPicture(EasyImage.java:197)
11-25 11:28:11.659 18439-18439/pl.aprilapps.easyphotopicker.sample W/System.err:     at pl.aprilapps.easyphotopicker.EasyImage.onPictureReturnedFromGallery(EasyImage.java:297)
11-25 11:28:11.659 18439-18439/pl.aprilapps.easyphotopicker.sample W/System.err:     at pl.aprilapps.easyphotopicker.EasyImage.handleActivityResult(EasyImage.java:244)
11-25 11:28:11.659 18439-18439/pl.aprilapps.easyphotopicker.sample W/System.err:     at pl.aprilapps.easyphotopicker.sample.MainActivity.onActivityResult(MainActivity.java:103)
11-25 11:28:11.659 18439-18439/pl.aprilapps.easyphotopicker.sample W/System.err:     at android.app.Activity.dispatchActivityResult(Activity.java:6475)
11-25 11:28:11.659 18439-18439/pl.aprilapps.easyphotopicker.sample W/System.err:     at android.app.ActivityThread.deliverResults(ActivityThread.java:3970)
11-25 11:28:11.659 18439-18439/pl.aprilapps.easyphotopicker.sample W/System.err:     at android.app.ActivityThread.handleSendResult(ActivityThread.java:4017)
11-25 11:28:11.659 18439-18439/pl.aprilapps.easyphotopicker.sample W/System.err:     at android.app.ActivityThread.access$1400(ActivityThread.java:172)
11-25 11:28:11.659 18439-18439/pl.aprilapps.easyphotopicker.sample W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1471)
11-25 11:28:11.659 18439-18439/pl.aprilapps.easyphotopicker.sample W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
11-25 11:28:11.659 18439-18439/pl.aprilapps.easyphotopicker.sample W/System.err:     at android.os.Looper.loop(Looper.java:145)
11-25 11:28:11.659 18439-18439/pl.aprilapps.easyphotopicker.sample W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5832)
11-25 11:28:11.659 18439-18439/pl.aprilapps.easyphotopicker.sample W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
11-25 11:28:11.659 18439-18439/pl.aprilapps.easyphotopicker.sample W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
11-25 11:28:11.659 18439-18439/pl.aprilapps.easyphotopicker.sample W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
11-25 11:28:11.659 18439-18439/pl.aprilapps.easyphotopicker.sample W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)```

**Comment by jkwiecien** [comment]
It works when the ```<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />``` is mandatory and not ```android:maxSdkVersion="18"```

Maybe let's not give the devs false hopes about avoiding this permission? :)

**Comment by MarcRubio** [comment]
Yea, samsungs can be problematic with things and I can't really test.

In any case, permissions should be used depending on the use case and it should be the developers responsibility in the end.

I simply wanted to allow the choice and also make devs aware of the possibility for using certain features without having to request permission. ie. Getting a picture directly from the camera and saving this inside the app directory "Context.getExternalFilesDir(String)" does not need any permission after sdk 18. Writing is performed by the camera application hence why the permission is not needed.

Anyway, I have made the mandatory write permission the default one in the manifest and provided warning comments in the MainActivity.

**Comment by jkwiecien** [comment]
There is no point doing such comment - nobody does app that can ignore samsungs. I'll accept the PR now but will make the permission mandatory and without any comments.

**Pull request merged**
