### PR TITLE
added optional chooser title

### PR DESCRIPTION
**Pull request by prempalsingh**
Signed-off-by: Prempal Singh <prempal.42@gmail.com>

### CODE REVIEW

**Comment by jkwiecien** [comment]
Forgot about this one. Title should not be optional. Could you please leave only the function with choserTitle param?

**Comment by prempalsingh** [comment]
Sure, I'll remove the extra functions.

**Comment by jkwiecien** [comment]
Will implement myself

**Comment by prempalsingh** [comment]
Why was my PR not merged? i made the required changes like you wanted.

**Comment by jkwiecien** [comment]
You were too late, your stuff was already done by me. Merged or not you have the features you wanted

**Comment by prempalsingh** [comment]
Well, I implemented it 3 hours before you said that you'll implement it yourself. And my code is exactly the same to what you wrote yourself. I wouldn't have sent a PR in the first place had I known you'd just close it.

**Comment by jkwiecien** [comment]
Yeah it seems like it, but I got the mail with the significant delay which made me think you were late. It is me who wasted the time doing the stuff already done, not you so what's the problem?

**Comment by prempalsingh** [comment]
Cool, no problem. :)

**Pull request closed without merging**
