### PR TITLE
Added possiblity to show gallery in chooser

### PR DESCRIPTION
**Pull request by maksim88**
Hey @jkwiecien, what do you think about a possiblity to show the gallery options inside a chooser?

Some people (like me) do not want to see the document chooser and would be able to choose between making a photo with the camera or choosing from galleries

### CODE REVIEW

**Comment by jkwiecien** [comment]
But that's what the ```openGallery``` is for, isn't it?

**Comment by maksim88** [comment]
But in `openGallery` the camera is missing inside the chooser. I needed the functionality that the same chooser shows a camera _and_ the gallery (instead of  documents)

**Comment by Rainer-Lang** [comment]
+1

**Comment by Rainer-Lang** [comment]
@jkwiecien Did you publish already a new version?

**Comment by jkwiecien** [comment]
No, hopefully today, still working on another requests

**Comment by jkwiecien** [comment]
Released now

**Comment by Rainer-Lang** [comment]
Thanks

**Pull request merged**
