### PR TITLE
Added ability to request image with custom requestCode.

### PR DESCRIPTION
**Pull request by pavlospt**

### CODE REVIEW

**Comment by pavlospt** [comment]
Hello @jkwiecien ! Did you have the time to check it?

**Comment by jkwiecien** [comment]
I didn't wan't to do it that way. Instead I made additional int type param. Will serve the same purpose. Should be there tomorrow

**Comment by pavlospt** [comment]
What is wrong with that way though?

**Comment by jkwiecien** [comment]
I just don't like the condition spamming.

**Pull request closed without merging**
